create table if not exists public.trip_checklist_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category text not null,
  title text not null,
  note text,
  sort_order integer not null default 0,
  is_checked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trip_checklist_items enable row level security;

create policy "Public can read checklist items"
on public.trip_checklist_items
for select
to anon
using (true);

create policy "Public can insert checklist items"
on public.trip_checklist_items
for insert
to anon
with check (true);

create policy "Public can update checklist items"
on public.trip_checklist_items
for update
to anon
using (true)
with check (true);

create policy "Public can delete checklist items"
on public.trip_checklist_items
for delete
to anon
using (true);

alter publication supabase_realtime add table public.trip_checklist_items;
