create table if not exists public.itinerary_items (
  id bigint generated by default as identity primary key,
  date date not null,
  day_label text not null,
  title text not null,
  time text not null default '00:00',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.itinerary_items enable row level security;

create policy "Public can read itinerary items"
on public.itinerary_items
for select
to anon
using (true);

create policy "Public can insert itinerary items"
on public.itinerary_items
for insert
to anon
with check (true);

create policy "Public can update itinerary items"
on public.itinerary_items
for update
to anon
using (true)
with check (true);

create policy "Public can delete itinerary items"
on public.itinerary_items
for delete
to anon
using (true);

alter publication supabase_realtime add table public.itinerary_items;
