create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  amount integer not null check (amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

create policy "Public can read expenses"
on public.expenses
for select
to anon
using (true);

create policy "Public can insert expenses"
on public.expenses
for insert
to anon
with check (true);

create policy "Public can delete expenses"
on public.expenses
for delete
to anon
using (true);

alter publication supabase_realtime add table public.expenses;
