create table if not exists public.travel_record_photos (
  id bigint generated by default as identity primary key,
  itinerary_id bigint not null references public.itinerary_items(id) on delete cascade,
  caption text,
  image_url text not null,
  storage_path text not null unique,
  file_name text,
  created_at timestamptz not null default now()
);

alter table public.travel_record_photos enable row level security;

create policy "Public can read travel record photos"
on public.travel_record_photos
for select
to anon
using (true);

create policy "Public can insert travel record photos"
on public.travel_record_photos
for insert
to anon
with check (true);

create policy "Public can delete travel record photos"
on public.travel_record_photos
for delete
to anon
using (true);

alter publication supabase_realtime add table public.travel_record_photos;

insert into storage.buckets (id, name, public)
values ('travel-records', 'travel-records', true)
on conflict (id) do nothing;

create policy "Public can view travel record bucket"
on storage.objects
for select
to anon
using (bucket_id = 'travel-records');

create policy "Public can upload travel record bucket"
on storage.objects
for insert
to anon
with check (bucket_id = 'travel-records');

create policy "Public can delete travel record bucket"
on storage.objects
for delete
to anon
using (bucket_id = 'travel-records');
